### ISSUE TITLE
Feature request - add new items

### ISSUE THREAD

**Issue by Tiagoquix** [stonecrusher/simpleMenuWizard#70] opened 2022-10-20 05:03 UTC
`#tracking-protection-icon-box` and `#tracking-protection-icon-container` to hide the Enhanced Tracking Protection shield from the URL bar.

`#eme-notification-icon` to hide the DRM icon from the URL bar.

`.openintabs-menuitem` and `.bookmarks-actions-menuseparator` to hide the "Open all in tabs" from bookmarks and its separator.

`#alltabs-button` to hide the all tabs button.

**Comment by stonecrusher** [comment] 2022-10-21 14:17
Hiding icons from the URL bar is out of scope for this project.
These guys may be interested or already have something like that in their repertoire: https://github.com/Aris-t2/CustomCSSforFx/

Do you have a screenshot for "Open all in tabs"? Not sure where it is. Because bookmarks sidebar already has those as option:
https://github.com/stonecrusher/simpleMenuWizard/blob/master/simpleMenuWizard/sidebar-context.css#L15

**Comment by stonecrusher** [comment] 2022-10-21 19:11
I cannot reproduce where that is. Your screenshot doesn't give context. Just censor what you don't want to be seen.
We're talking about FF106.1?

However, if it's not a context menu I will probably not add it to the project. And I remember removing stuff from the bookmarks toolbar itself most of the time didn't work properly.

Have you managed removing it for yourself?

**Closed** 2022-10-21 19:17 UTC
